#!/bin/zsh

PGPASSWORD=cooktop
set -euo pipefail

if [[ -n "${DEBUG:-}" ]]; then
	set -x
fi

validuser(){ [[ -n $(id -u "$1" 2>/dev/null) ]] && echo 1 || echo 0; }

function addUsers {
	sudo -i
	if [validuser('cooktop')]; then
		adduser cooktop
	fi
	usermod -a -G adm, sudo
	su cooktop -c "createuser -w -d -r -s cooktop"
	su cooktop -c "createdb -O cooktop cooktop"
}

addUsers

DB_NAME='cooktop'

readonly DB_SUFFIXES=(
	'test'
	'development'
)

declare -a pgopts=(--host localhost --port 5442 --user cooktop)

for suffix in "${DB_SUFFIXES[@]}"; do
	dbname="${DB_NAME}_${suffix}"
	if psql "${pgopts[@]}" --dbname "$dbname" -c '' ; then
		echo "$dbname is online"
	else
		createdb "${pgopts[@]}" "${DB_NAME}_${suffix}"
	fi
	declare -a psqldb=(psql "${pgopts[@]}" --dbname "$dbname")
done